# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=b'Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'pedidos/images', verbose_name=b'Imagem')),
            ],
            options={
                'verbose_name': 'Tipo de Pedido',
                'verbose_name_plural': 'Tipos de Pedido',
            },
        ),
    ]
