# Generated by Django 2.1.4 on 2019-01-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20190126_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, max_length=200, verbose_name='Observação'),
        ),
    ]
