# Generated by Django 2.0 on 2019-02-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_caravaneiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='caravaneiro',
        ),
        migrations.AddField(
            model_name='type',
            name='caravaneiro',
            field=models.BooleanField(default=False),
        ),
    ]
