# Generated by Django 2.1.4 on 2019-01-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedinte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Empresa'),
        ),
    ]
