# Generated by Django 2.1.4 on 2019-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='recebeu',
            field=models.BooleanField(default=False),
        ),
    ]
