# Generated by Django 2.1.4 on 2019-01-16 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=50)),
                ('confirmar_senha', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('foto', models.FileField(blank=True, null=True, upload_to='core/static/media/Fotos_Perfil/', verbose_name='Foto')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=50)),
                ('confirmar_senha', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('foto', models.FileField(blank=True, null=True, upload_to='core/static/media/Fotos_Perfil/', verbose_name='Foto')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=16, null=True)),
                ('valor', models.FloatField(max_length=200)),
                ('peso', models.FloatField(default=0.0, max_length=32)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('UFDestino', models.CharField(max_length=2)),
                ('regiaoDestino', models.CharField(choices=[('C', 'Capital'), ('I', 'Interior')], max_length=1)),
                ('cliente', models.CharField(blank=True, max_length=30)),
                ('data_conemb', models.DateField(auto_now=True)),
                ('data_ocoren', models.DateField(auto_now=True)),
                ('data_previsao', models.DateField(auto_now=True)),
                ('prazo', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Entregue', 'Entregue'), ('Encaminhado', 'Encaminhado')], default='Pendente', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('UF', models.CharField(max_length=2)),
                ('inicioCEP', models.CharField(max_length=8)),
                ('fimCEP', models.CharField(max_length=8)),
                ('prazoSEDEX', models.IntegerField()),
                ('prazoPAC', models.IntegerField()),
                ('regiao', models.CharField(choices=[('C', 'Capital'), ('I', 'Interior')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacaoTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('prazoEstimado', models.IntegerField(default=0, null=True)),
                ('precoEstimado', models.FloatField(default=0, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacao_transporte', to='core.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=50)),
                ('confirmar_senha', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('foto', models.FileField(blank=True, null=True, upload_to='core/static/media/Fotos_Perfil/', verbose_name='Foto')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RastreamentoArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=16)),
                ('tipo', models.CharField(choices=[('CONEMB', 'CONEMB'), ('OCOREN', 'OCOREN')], max_length=8)),
                ('codigo', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('Finalizado', 'FINALIZADO'), ('Problema na Entrega', 'PROBLEMA NA ENTREGA'), ('Encaminhado', 'ENCAMINHADO')], max_length=32)),
                ('arquivo', models.FileField(upload_to='core/static/media/Rastreamento/')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('arquivo', models.FileField(null=True, upload_to='core/arquivos/')),
            ],
        ),
        migrations.CreateModel(
            name='RegraDeNegocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=200)),
                ('UF', models.CharField(max_length=2)),
                ('regiao', models.CharField(choices=[('C', 'Capital'), ('I', 'Interior')], max_length=1)),
                ('preco', models.IntegerField(null=True)),
                ('prazo', models.IntegerField(null=True)),
                ('performance', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela_Capital_Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('peso', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela_Capital_Interior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('peso', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela_Interior_Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('peso', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela_Interior_Interior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('peso', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela_Prazos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='core/static/media/TabelaPrazo/')),
            ],
        ),
        migrations.CreateModel(
            name='Tabela_Precos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='core/static/media/TabelaPreco/')),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('CNPJ', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(blank='True', max_length=16)),
                ('valorMaximo', models.FloatField(blank='True', null=True)),
                ('valorAtual', models.FloatField(default=0, null=True)),
                ('maximoPedidos', models.IntegerField(blank='True', null=True)),
                ('quantidadeAtual', models.IntegerField(default=0, null=True)),
                ('logo', models.ImageField(default='media/transportadoras/default.png', upload_to='media/transportadoras')),
                ('preco', models.FloatField(blank='True', null=True)),
                ('performance', models.IntegerField(blank='True', default=100, null=True)),
                ('rankingPreco', models.FloatField(blank='True', null=True)),
                ('rankingPrazo', models.FloatField(blank='True', null=True)),
                ('rankingPerformance', models.FloatField(blank='True', null=True)),
                ('rankingGeral', models.FloatField(blank='True', null=True)),
                ('regiaoDeAtuacao', models.CharField(blank='True', max_length=10, null=True)),
                ('adValorem', models.FloatField(null=True)),
                ('regiao', multiselectfield.db.fields.MultiSelectField(choices=[('SUL', 'Sul'), ('SUDESTE', 'Sudeste'), ('CENTROOESTE', 'Centro-Oeste'), ('NORTE', 'Norte'), ('NORDESTE', 'Nordeste')], default='SUL', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('capital_interior', models.CharField(max_length=2)),
                ('peso', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('origem', models.CharField(max_length=2)),
                ('regiaoDeAtuacao', models.CharField(max_length=10)),
                ('transportadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Transportadora')),
            ],
        ),
        migrations.AddField(
            model_name='tabela_precos',
            name='transportadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Transportadora'),
        ),
        migrations.AddField(
            model_name='tabela_prazos',
            name='transportadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Transportadora'),
        ),
        migrations.AddField(
            model_name='tabela_interior_interior',
            name='transportadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Transportadora'),
        ),
        migrations.AddField(
            model_name='tabela_interior_capital',
            name='transportadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Transportadora'),
        ),
        migrations.AddField(
            model_name='tabela_capital_interior',
            name='transportadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Transportadora'),
        ),
        migrations.AddField(
            model_name='tabela_capital_capital',
            name='transportadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Transportadora'),
        ),
        migrations.AddField(
            model_name='programacaotransporte',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Registro'),
        ),
        migrations.AddField(
            model_name='programacaotransporte',
            name='transportadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Transportadora'),
        ),
        migrations.AddField(
            model_name='prazo',
            name='transportadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Transportadora'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Registro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Transportadora'),
        ),
    ]
