# Generated by Django 2.1.5 on 2019-02-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='texto',
            field=models.CharField(max_length=10000, verbose_name='Texto'),
        ),
    ]
