# Generated by Django 2.1.4 on 2019-01-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
