# Generated by Django 2.1.5 on 2019-02-06 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='organizador_resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_organizador', to='usuarios.Organizador'),
        ),
    ]
