# Generated by Django 2.1.5 on 2019-01-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.IntegerField()),
                ('tamanho', models.IntegerField(choices=[(0, '9 m2'), (1, '10 m2'), (2, '10,5 m2'), (3, '12 m2'), (4, '14 m2'), (5, '20 m2'), (6, '25,5 m2'), (7, '30 m2'), (8, '40 m2'), (9, '51,5 m2')])),
                ('palestra', models.BooleanField(default=False)),
                ('cnpj', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_gerente', to='usuarios.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_organizador', to='usuarios.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='organizador_resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Organizador'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empresa', to='usuarios.Usuario'),
        ),
    ]
