# Generated by Django 2.1.4 on 2019-02-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190206_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizador',
            options={'verbose_name': 'Organizador', 'verbose_name_plural': 'Organizadores'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='recebeu_mensagem',
            field=models.BooleanField(default=False),
        ),
    ]
