# Generated by Django 2.1.4 on 2019-02-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190211_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='recebeu_mensagem',
            new_name='enviou_mensagem',
        ),
    ]
