# Generated by Django 2.1 on 2019-01-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_empresa_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizador',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizador',
            name='sobrenome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizador',
            name='telefone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
