# Generated by Django 2.1 on 2019-01-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20190127_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='email',
            field=models.EmailField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizador',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizador',
            name='sobrenome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizador',
            name='telefone',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
