# Generated by Django 2.0 on 2019-03-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('sistema_wi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_empresa', to='usuarios.Empresa')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='sistema_wi.LinkFeed')),
            ],
        ),
    ]
