# Generated by Django 2.1.2 on 2019-02-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_wi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoresestaticos',
            name='n_salas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='valoresestaticos',
            name='horario_massagem_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='valoresestaticos',
            name='horario_massagem_inicio',
            field=models.TimeField(),
        ),
    ]
