# Generated by Django 2.1.4 on 2019-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_wi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoresestaticos',
            options={'verbose_name': 'Valores Estaticos', 'verbose_name_plural': 'Valores Estaticos'},
        ),
        migrations.AddField(
            model_name='valoresestaticos',
            name='data_de_inicio',
            field=models.DateField(null=True),
        ),
    ]
