# Generated by Django 2.0 on 2019-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_wi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresestaticos',
            name='nome_wifi',
            field=models.CharField(default='polijunior', max_length=100),
        ),
        migrations.AlterField(
            model_name='valoresestaticos',
            name='senha_wifi',
            field=models.CharField(default='polijunior', max_length=100),
        ),
    ]
