# Generated by Django 2.1.4 on 2019-02-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_wi', '0002_auto_20190205_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresestaticos',
            name='data_de_inicio',
            field=models.DateField(default=None),
        ),
    ]
