# Generated by Django 2.1.5 on 2019-02-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_wi', '0002_auto_20190219_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafeed',
            options={'verbose_name': 'dataFeed', 'verbose_name_plural': 'dataFeeds'},
        ),
        migrations.AlterField(
            model_name='datafeed',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='datafeed',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='link'),
        ),
    ]
