# Generated by Django 2.1.5 on 2019-02-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_wi', '0003_auto_20190205_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoresestaticos',
            name='mapa_wi',
            field=models.ImageField(blank=True, null=True, upload_to='sistema_wi/fotos'),
        ),
    ]
